# whitelist
branches:
  only:
    - master
    - /^test.*$/

os:
  - linux

language: generic

env:
- PY=2.7

notifications:
  email: false

before_install:
- OS=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "MacOSX"; else echo "Linux"; fi)
- wget "https://repo.continuum.io/miniconda/Miniconda-latest-$OS-x86_64.sh" -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- PATHPREFIX=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "/Users/travis/miniconda/bin"; else echo "/home/travis/miniconda/bin"; fi)
- export PATH=$PATHPREFIX:$PATH
- conda update --yes conda

install:
- conda install --yes python=$PY
- pip install coveralls
- pip install .

script:
- testflo . --coverage --coverpkg testflo
- ls -ltra
- cat .coverage*

after_success:
- coveralls debug
- coveralls
